/robot_news_station_glskard:
  ros__parameters:
    robot_name: "glskard"

/robot_news_station_bb8:
  ros__parameters:
    robot_name: "bb8"

/robot_news_station_c3po:
  ros__parameters:
    robot_name: "c3po"

/robot_news_station_lander:
  ros__parameters:
    robot_name: "lander"